//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Rainbow ObjectFlow")]
[assembly: AssemblyDescription("Fluent workflow frameworks")]
[assembly: AssemblyCompany("RainbowSoft")]
[assembly: AssemblyProduct("Rainbow.ObjectFlow")]
[assembly: AssemblyCopyright("Copyright © G.Moore 2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("d14b6bea-3ec7-4db0-ad6d-ebec4a192d9f")]
[assembly: AssemblyVersion("1.3.1.1")]
[assembly: AssemblyFileVersion("1.3.1.1")]


